### ISSUE TITLE
Reordenar filtros en las siguientes pantallas: "Lista de existencia", "Salidas de Inventario", "Kardex"

### ISSUE THREAD

**Issue by alvarogarcia1010** [mgallegos/decima-inventory#47]

**Comment by alvarogarcia1010** [comment]
Revisar si falta algo!

**Comment by mgallegos** [comment]
En listado de existencia verifica que el campo color y talla esten apuntando a la columna correcta y quita el campo de ancho, agrega el filtro "segmento" que sea un campo de texto normal (like) y colocalo a la izquierda de color.

**Comment by mgallegos** [comment]
En salidas de inventario, agrega los de marca, modelo y segmento, quita el del ancho.

**Comment by mgallegos** [comment]
En Kardex, agrega los de marca, modelo, segmento, grupo y subgrupo, quita el del ancho.

**Comment by mgallegos** [comment]
Cambiar etiqueta Producto por Artículo.

**Comment by alvarogarcia1010** [comment]
Revisar!

**Comment by mgallegos** [comment]
Todo bien
