### ISSUE TITLE
Agregar nuevos campos en pantalla de conf. incial

### ISSUE THREAD

**Issue by mgallegos** [mgallegos/decima-inventory#54]
Agregar al final la sección "Importación de movimientos" los campos:
- Carpeta de archivos (mi_folder_id, autocomplete FolderManager - decima-file)
- Filas de encabezado (mi_header_rows_number, validador positiveInteger con maxlength de 2)
- Columna de cantidad (mi_internal_reference_column, maxlength de 1)
- Columna de código (mi_quantity_column, maxlength de 1)
- Columna de costo (mi_cost_column, maxlength de 1)
- Columna de precio (mi_price_column, maxlength de 1)
- Columna de observación (mi_remark_column, maxlength de 1)

Script:
```
ALTER TABLE `INV_Setting` 
ADD COLUMN `mi_folder_id` INT(10) UNSIGNED NULL DEFAULT NULL AFTER `requisition_user_id`,
ADD COLUMN `mi_header_rows_number` TINYINT NULL DEFAULT NULL AFTER `mi_folder_id`,
ADD COLUMN `mi_internal_reference_column` CHAR(1) NULL DEFAULT NULL AFTER `mi_header_rows_number`,
ADD COLUMN `mi_quantity_column` CHAR(1) NULL DEFAULT NULL AFTER `mi_internal_reference_column`,
ADD COLUMN `mi_cost_column` CHAR(1) NULL DEFAULT NULL AFTER `mi_quantity_column`,
ADD COLUMN `mi_price_column` CHAR(1) NULL DEFAULT NULL AFTER `mi_cost_column`,
ADD COLUMN `mi_remark_column` CHAR(1) NULL DEFAULT NULL AFTER `mi_price_column`;

**Comment by alvarogarcia1010** [comment]
Falta el autocomplete de folder y arreglar los journals

**Comment by alvarogarcia1010** [comment]
Listo!

**Comment by alvarogarcia1010** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Agregar nuevos campos en pantalla de conf. incial](https://trello.com/c/Wwgnrrgd/28-agregar-nuevos-campos-en-pantalla-de-conf-incial)
