### ISSUE TITLE
Desarrollar pantalla de Gestión de Movimientos

### ISSUE THREAD

**Issue by mgallegos** [mgallegos/decima-inventory#6]
Controlador
     MovementManager.php

Repositorio: 
    EloquentMovement.php y EloquentMovementEntry.php

Servicio:
    MovementManager.php

Vista: 
    movement-manager.blade.php

Modelo: 
    UnitMeasure.php y UnitMeasureConversion.php

Prefijos: 
    inv-mm-, invMm, inv_mm_ y  inv-mm-me-, invMmMe, inv_mm_me_

**Comment by mgallegos** [comment]
Recursos:
- [Vista de libro diario](https://github.com/mgallegos/decima-accounting/blob/master/src/views/journal-management.blade.php)
- [Controlador de libro diario](https://github.com/mgallegos/decima-accounting/blob/master/src/Mgallegos/DecimaAccounting/Accounting/Controllers/JournalManager.php)
- [Servicio de libro diario](https://github.com/mgallegos/decima-accounting/blob/master/src/Mgallegos/DecimaAccounting/Accounting/Services/JournalManagement/JournalManager.php)

**Comment by mgallegos** [comment]
Ejemplo para calcular el número del movimiento:
- [Servicio](https://github.com/mgallegos/decima-asset/blob/master/src/Mgallegos/DecimaAsset/Asset/Services/MovementManagement/MovementManager.php#L257)
- [Repositorio](https://github.com/mgallegos/decima-asset/blob/master/src/Mgallegos/DecimaAsset/Asset/Repositories/Movement/EloquentMovement.php#L84)

**Comment by AlejandroJuarez97** [comment]
Falta agregar el servicio de proveedores solamente.
