### ISSUE TITLE
Desarrollar pantalla de Gestión de Tipos de Movimientos

### ISSUE THREAD

**Issue by mgallegos** [mgallegos/decima-inventory#9]
Controlador
     MovementTypeManager.php

Repositorio: 
    MovementType.php

Servicio:
    MovementTypeManager.php

Vista: 
    movement-type-management.blade.php

Modelo: 
    MovementType.php

Prefijos: 
     inv-mtm-, invMtm, inv_mtm_

**Comment by arcp** [comment]
Esta pantalla en que boton del menu ira???

2016-10-07 9:26 GMT-06:00 Mario Gallegos <notifications@github.com>:

**Comment by mgallegos** [comment]
Ya los voy a revisar, creo que falta crearlos.
